name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 禁止浅克隆，拿到完整 git 历史

          - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      # Spring Boot 3.x 兼容，若你pom强制17可改成'17'
          cache: 'maven'

      - name: Build & Test with Maven
        run: mvn -B -DskipTests=false verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests \
            -Dsonar.organization=ningchangliu \
            -Dsonar.projectKey=NINGCHANGLIU_iwvg-devops-liu-ningchang \
            -Dsonar.host.url=https://sonarcloud.io