name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      # Spring Boot 3.x 兼容，若你pom强制17可改成'17'
          cache: 'maven'

      - name: Build & Test with Maven
        run: mvn -B -DskipTests=false verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # 你在 GitHub Secrets 里刚建的
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests
